# Copyright (c) 2022 MobileCoin Inc.

name: 'k8s-toolbox'
description: 'K8s tools for MobileCoin infrastructure.'
inputs:
  action:
    description: "builtin action to run (See README.md)"
    required: true
  chart_app_version:
    description: "chart appVersion for publish"
    required: false
  chart_name:
    description: "name of chart in repo"
    required: false
  chart_path:
    description: "Path to chart files for publish"
    required: false
  chart_repo:
    description: "url for chart repo"
    required: false
  chart_repo_username:
    description: "Username for private chart repo"
    required: false
  chart_repo_password:
    description: "Password for private chart repo"
    required: false
  chart_set:
    description: "new line list of --set commands"
    required: false
  chart_values:
    description: "values file path for chart release"
    required: false
  chart_version:
    description: "chart version"
    required: false
  chart_wait_timeout:
    description: "timeout to wait for resources to be healthy"
    required: false
    default: "10m"
  command:
    description: "shell commands to run"
    required: false
  debug:
    description: Enable debug logging
    required: false
  dst:
    description: "File destination to copy into toolbox"
    required: false
  fog_keys_seed:
    description: "seed to recreate fog keys with sample-keys"
    required: false
  fog_report_signing_ca_cert:
    description: "CA certificate for fog-report signing certs"
    required: false
  ingest_color:
    description: "Ingest blue or green"
    required: false
  initial_keys_seed:
    description: "seed to recreate initial keys with sample-keys"
    required: false
  namespace:
    description: "kubernetes namespace"
    required: false
  object_name:
    description: "k8s object to manipulate"
    required: false
  rancher_project:
    description: "rancher project"
    required: false
    default: "default"
  rancher_cluster:
    description: "Rancher K8s Cluster"
    required: false
  rancher_token:
    description: "Rancher Auth Token"
    required: false
  rancher_url:
    description: "Rancher management url"
    required: false
  release_name:
    description: "helm release name"
    required: false
  src:
    description: "File to copy into toolbox"
    required: false
runs:
  using: docker
  # image: Dockerfile
  image: docker://mobilecoin/gha-k8s-toolbox:v1.0
  args:
  - ${{ inputs.command }}
