# Copyright (c) 2022 MobileCoin Inc.
name: build-and-publish

on:
  push:
    tags:
    - 'v*.*.*'
  pull_request: {}

env:
  DOCKER_REPO: mobilecoin/gha-k8s-toolbox

jobs:
  docker:
    runs-on: mco-dev-small-x64
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Publish Docker
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        flavor: latest=true
        images: ${{ env.DOCKER_REPO }}
        tags: |
          type=ref,event=pr,priority=30
          type=semver,pattern=v{{major}},priority=22
          type=semver,pattern=v{{major}}.{{minor}},priority=21
          type=semver,pattern=v{{version}},priority=20
          type=sha,priority=10
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        push: ${{ github.event_name == 'pull_request' && 'false' || 'true' }}
        dockerfile: Dockerfile
