# Copyright (c) 2022 MobileCoin Inc.
name: release

on:
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: write

jobs:
  gh-release:
    runs-on: mco-dev-small-x64
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0
    - name: Create a GitHub Release
      uses: mobilecoinofficial/gh-actions/gh-release@v0
      with:
        generate_release_notes: true
