# Copyright (c) 2022 MobileCoin Inc.
name: tag

on:
  push:
    branches:
    - main

jobs:
  tag:
    runs-on: mco-dev-small-x64
    steps:
    # We need to use an external PAT here because GHA will not run downstream events if we use the built in token.
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}

    - name: Bump GitHub tag
      id: bump
      uses: mobilecoinofficial/gh-actions/tag@v0
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}
        with_v: 'true'
        default_bump: patch

    # Push major and minor tags because anothrNick/github-tag-action won't retag a commit.
    - name: Get major and minor values for new tag
      id: tags
      env:
        TAG: ${{ steps.bump.outputs.new_tag }}
      run: |
        export MAJOR_MINOR=${TAG%.*}
        export MAJOR=${MAJOR_MINOR%.*}
        git tag --force "${MAJOR}"
        git tag --force "${MAJOR_MINOR}"
        git push --tags --force
