# Copyright (c) 2022 MobileCoin Inc.
name: tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: [self-hosted, Linux, small]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # We need to use an external PAT here because GHA will not run downstream events if we use the built in token.
    - name: Bump GitHub tag
      id: bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        WITH_V: "true"
        DEFAULT_BUMP: patch

    # Use built in token here because we don't need downstream events for these tags.
    # Doing manual tag because anothrNick/github-tag-action won't retag a commit.
    - name: Get major and minor values for new tag
      id: tags
      env:
        TAG: ${{ steps.bump.outputs.tag }}
      run: |
        export MAJOR_MINOR=${TAG%.*}
        export MAJOR=${MAJOR_MINOR%.*}
        git tag "${MAJOR_MINOR}"
        git tag "${MAJOR}"
        git push --tags
